routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Route::get('indipay/response','Auth\register@response');
Route::post('indipay/response','Auth\register@response');



//Route::get('success', 'Auth\register@response')->name('admin.success');


/*Route::get('admin/register', function () {
    return view('admin.register');
});

Route::delete('admin/register', function(){
    re
});

Route::post('admin/register', 'Auth\register@store')->name('register.submit');*/

Route::resource('admin/register','Auth\register');

Auth::routes();
Route::get('/epin', 'epinController@generateepin')->name('admin.epin');
Route::get('/viewepin', 'epinController@viewepin')->name('admin.viewepin');



Route::resource('home', 'HomeController');

Route::prefix('admin')->group(function (){

    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/updateprofilepicture', 'ProfileUpdate@updateprofilepicture')->name('image.dashboard');

   // Route::put('/', 'AdminController@update')->name('admin.update.submit');
    //Route::get('/profile', 'AdminController@profile');
    Route::resource('/profile', 'ProfileUpdate');
    
 //   Route::get('/', 'AdminController@index');ProfileUpdate

});

app/Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;
    protected $guard = 'admin';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'job_title',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Epin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Epin extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;
use Auth;
use App\User;
use App\Admin;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
        public function index()
    {

        {
           

            return view('admin.pages.dashboard');
        }

        // return view('admin');
    }
    
       public function edit($id)
    {
        // find the post in the database and save as a var
        $admin = Admin::find($id);
        // return the view and pass in the var we previously created
        return view('admin')->withAdmin($admin);
    }
    

    public function profile() {




        return view('admin.pages.profile');

}

    
 
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Admin;
//use App\Http\Requests;

use Session;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::orderBy('id', 'desc')->paginate(300);
        return view('dashboard')->withAdmins($admins);

      //  $posts = Post::orderBy('id', 'desc')->paginate(10);
       // return view('dashboard')->withPosts($posts);
    }

    public function show($id)
    {
        $admins = Admin::orderBy('id', 'desc')->paginate(300);
        return view('dashboard')->withAdmins($admins);
    }

    public function edit($id)
    {
        // find the post in the database and save as a var
        $admin = Admin::find($id);

        // return the view and pass in the var we previously created
        return view('user.edit')->withAdmin($admin);
    }

    public function update(Request $request, $id)
    {
 
         
        $admin = Admin::find($id);


        $admin->earning = $request->earning;


        $admin->save();




        return redirect('home');
 
    }
}

app/Http/Controllers/ProfileUpdate.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use App\Admin;
use Auth;

class ProfileUpdate extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index() {




        return view('admin.pages.profile');

}

    public function edit($id)
    {
        // find the post in the database and save as a var
        $admin = Admin::find($id);

        // return the view and pass in the var we previously created
        return view('admin.pages.profile')->withAdmin($admin);
    }

    public function update(Request $request, $id)
    {




        $admin = Admin::find($id);

        $photoName = time().'.'.$request->image->getClientOriginalExtension();
        $request->image->move(public_path('uploads'), $photoName);



        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->mobile = $request->mobile;
        $admin->address = $request->address;
        $admin->bank_acc = $request->bank_acc;
        $admin->bank_name = $request->bank_name;
        $admin->ifsc = $request->ifsc;
        $admin->img = $photoName;

        $admin->save();





        return redirect('admin');

    }



    public function updateprofilepicture(Request $request, $id)
    {




        $admin = Admin::find($id);

        $photoName = time().'.'.$request->image->getClientOriginalExtension();
        $request->image->move(public_path('uploads'), $photoName);




        $admin->img = $photoName;

        $admin->save();





        return redirect('admin');

    }





/*
public function profileupdate() {

}*/



}

app/Http/Controllers/epinController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Epin;
use Auth;
class epinController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    public function generateepin (Request $request ) {
        $newepin =  uniqid(rand(), true);

        $epin = new Epin();
        $epin -> epin = $newepin;
        $epin -> user_id = Auth::user()->id;
        $epin->save();
        return redirect('viewepin');

    }

    public function viewepin() {

        $epins = Epin::orderBy('id', 'desc')->paginate(300);

        return view('user.show')->withEpins($epins);
    }
}

resources/views/admin.blade.php
<!DOCTYPE html>
<head>
    <title>Management Pannel Phamtom Money</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- bootstrap-css -->
    <link rel="stylesheet" href="css/bootstrap.min.css" >
    <!-- //bootstrap-css -->
    <!-- Custom CSS -->
    <link href="css/style.css" rel='stylesheet' type='text/css' />
    <link href="css/style-responsive.css" rel="stylesheet"/>
    <!-- font CSS -->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="css/font.css" type="text/css"/>
    <link href="css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="css/morris.css" type="text/css"/>
    <!-- calendar -->
    <link rel="stylesheet" href="css/monthly.css">
    <!-- //calendar -->
    <!-- //font-awesome icons -->
    <script src="js/jquery2.0.3.min.js"></script>
    <script src="js/raphael-min.js"></script>
    <script src="js/morris.js"></script>
</head>
<body>
<section id="container">
    <!--header start-->
    <header class="header fixed-top clearfix">
        <!--logo start-->
        <div class="brand">
            <a href="/" class="logo">
                Phamtom
            </a>
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars"></div>
            </div>
        </div>
        <!--logo end-->
        <div class="nav notify-row" id="top_menu">
            <!--  notification start -->
            <ul class="nav top-menu">
                <!-- settings start -->

                <!-- notification dropdown end -->
            </ul>
            <!--  notification end -->
        </div>
        <div class="top-nav clearfix">
            <!--search & user info start-->
            <ul class="nav pull-right top-menu">
                <li>
                    <input type="text" class="form-control search" placeholder=" Search">
                </li>
                <!-- user login dropdown start-->
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <img alt="" src="images/2.png">
                        <span class="username">{{ Auth::user()->name }}</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu extended logout">
                        <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                        <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                        <li><a href="login.html"><i class="fa fa-key"></i> Log Out</a></li>
                    </ul>
                </li>
                <!-- user login dropdown end -->

            </ul>
            <!--search & user info end-->
        </div>
    </header>
    <!--header end-->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse">
            <!-- sidebar menu start-->
            <div class="leftside-navigation">
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a class="active" href="index.html">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="fa fa-book"></i>
                            <span>User Profile</span>
                        </a>

                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-bullhorn"></i>
                            <span>Referls </span>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="fa fa-bullhorn"></i>
                            <span>Generate EPIN </span>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="fa fa-bullhorn"></i>
                            <span>Generate EPIN </span>
                        </a>
                    </li>
                </ul>            </div>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">

            <h1 style="color: white"> Hi {{ Auth::user()->name }}, </h1>
            <h1> Sorry for inconvience caused we are currently working on this pannel. Inconvience Regretted </h1>
            <!-- //market-->
            <div class="market-updates">
                <div class="col-md-3 market-update-gd">
                    <div class="market-update-block clr-block-2">
                        <div class="col-md-4 market-update-right">
                            <i class="fa fa-eye"> </i>
                        </div>
                        <div class="col-md-8 market-update-left">
                            <h4>Refered by</h4>
                            <h4>+91 {{ Auth::user()->ref }}</h4>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="col-md-3 market-update-gd">
                    <div class="market-update-block clr-block-1">
                        <div class="col-md-4 market-update-right">
                            <i class="fa fa-users" ></i>
                        </div>
                        <div class="col-md-8 market-update-left">
                            <h4>Users under you</h4>
                            <h3>Coming Soon</h3>
                            <p></p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="col-md-3 market-update-gd">
                    <div class="market-update-block clr-block-3">
                        <div class="col-md-4 market-update-right">
                            <i class="fa fa-usd"></i>
                        </div>
                        <div class="col-md-8 market-update-left">
                            <h4>Your Income</h4>
                            <h3><i class="fa fa-inr" aria-hidden="true"></i> {{ Auth::user()->earning }}</h3>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="col-md-3 market-update-gd">
                    <div class="market-update-block clr-block-4">
                        <div class="col-md-4 market-update-right">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        </div>
                        <div class="col-md-8 market-update-left">
                            <h4>Orders</h4>
                            <h4>You Bought <br><span style="color: greenyellow"><i class="fa fa-inr" aria-hidden="true"></i> {{ Auth::user()->plan }} Plan</span></h4>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <!-- //market-->



                <div class="clearfix"> </div>
            </div>
        </section>
        <!-- footer -->
        <div class="footer">
            <div class="wthree-copyright">
                <p>© 2017 Visitors. All rights reserved</p>
            </div>
        </div>
        <!-- / footer -->
    </section>
    <!--main content end-->
</section>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.dcjqaccordion.2.7.js"></script>
<script src="js/scripts.js"></script>
<script src="js/jquery.slimscroll.js"></script>
<script src="js/jquery.nicescroll.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="js/jquery.scrollTo.js"></script>
<!-- morris JavaScript -->
<script>
    $(document).ready(function() {
        //BOX BUTTON SHOW AND CLOSE
        jQuery('.small-graph-box').hover(function() {
            jQuery(this).find('.box-button').fadeIn('fast');
        }, function() {
            jQuery(this).find('.box-button').fadeOut('fast');
        });
        jQuery('.small-graph-box .box-close').click(function() {
            jQuery(this).closest('.small-graph-box').fadeOut(200);
            return false;
        });

        //CHARTS
        function gd(year, day, month) {
            return new Date(year, month - 1, day).getTime();
        }

        graphArea2 = Morris.Area({
            element: 'hero-area',
            padding: 10,
            behaveLikeLine: true,
            gridEnabled: false,
            gridLineColor: '#dddddd',
            axes: true,
            resize: true,
            smooth:true,
            pointSize: 0,
            lineWidth: 0,
            fillOpacity:0.85,
            data: [
                {period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649},
                {period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051},
                {period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910},
                {period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695},
                {period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300},
                {period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891},
                {period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598},
                {period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185},
                {period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038},

            ],
            lineColors:['#eb6f6f','#926383','#eb6f6f'],
            xkey: 'period',
            redraw: true,
            ykeys: ['iphone', 'ipad', 'itouch'],
            labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],
            pointSize: 2,
            hideHover: 'auto',
            resize: true
        });


    });
</script>
<!-- calendar -->
<script type="text/javascript" src="js/monthly.js"></script>
<script type="text/javascript">
    $(window).load( function() {

        $('#mycalendar').monthly({
            mode: 'event',

        });

        $('#mycalendar2').monthly({
            mode: 'picker',
            target: '#mytarget',
            setWidth: '250px',
            startHidden: true,
            showTrigger: '#mytarget',
            stylePast: true,
            disablePast: true
        });


    });
</script>
<!-- //calendar -->
</body>
</html>

resources/views/admin/pages/dashboard.blade.php
@extends('admin.index')

@section('content')

    <div class="page-title">
        <h3>Dashboard</h3>
        <div class="page-breadcrumb">
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </div>
    <div id="main-wrapper">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p>Rs {{ Auth::user()->earning }}</p>
                            <span class="info-box-title">Last Week Earning</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="icon-users"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p>Rs {{ Auth::user()->plan }}</p>
                            <span class="info-box-title">Your Plan</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="icon-eye"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p>{{ Auth::user()->ref }}</p>
                            <span class="info-box-title">Your Referal</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="icon-basket"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel info-box panel-white">
                    <div class="panel-body">
                        <div class="info-box-stats">
                            <p class="counter">-</p>
                            <span class="info-box-title">Last Month Earning</span>
                        </div>
                        <div class="info-box-icon">
                            <i class="icon-envelope"></i>
                        </div>
                        <div class="info-box-progress">
                            <div class="progress progress-xs progress-squared bs-n">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- Row -->


    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-white todo">
                    <div class="panel-body">
                    </div>

                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/admin/pages/profilepicture.blade.php
@extends('admin.index')

@section('content')
    <div id="main-wrapper">
        <div class="row">

            <div class="col-md-12">

                <form action="{{url('admin/profile/' . $admin->id)}}"  enctype="multipart/form-data" method="post" >
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">






        <div >

           <img class="center" src="../../../../uploads/{{ $admin->img }}" width="250px" >
        </div>

        <div class="form-group">
            <label for="name">Profile</label>
            <input type="file" name="image" required value="" class="form-control">
        </div>










        <button type="submit" class="btn btn-primary">
            <i class="fa fa-btn fa-sign-in"></i>Update
        </button>
    </form>
            </div>
        </div>
    </div>

    @endsection

resources/views/admin/pages/viewepin.blade.php
@extends('admin.index')

@section('content')





<table class="table no-cellborder">
    <thead>
    <tr><th>Id</th><th> Epin</th><th>User</th></tr>
    </thead>
    <tbody>
    @foreach ($epins as $epin)
        <tr>
            <td class="text-primary">{{ $epin->id}}</td>
            <td class="text-primary">{{ $epin->epin}}</td>
            <td class="text-primary">{{ $epin->user_id}}</td>
        </tr>
    @endforeach
    </tbody>
</table>

    @endsection

resources/views/admin/register.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('register.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">Mobile</label>

                                <div class="col-md-6">
                                    <input id="tel" type="tel" class="form-control" name="mobile" value="" required>

                                </div>
                            </div>


                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">Referal Mobile Number</label>

                                <div class="col-md-6">
                                    <input id="tel" type="text" class="form-control" name="ref" value="" required>

                                </div>
                            </div>--}}

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">Epin</label>

                                <div class="col-md-6">
                                    <input id="tel" type="tel" class="form-control" name="epin" value="">

                                </div>
                            </div>

                        <h2 class="text-center" style="align-content: center">OR</h2>



                            <div class="form-group ">
                                <label for="email" class="col-md-4 control-label">Online Payment</label>
                                <div class="col-md-6">
                                <select name="plan" class="form-control">
                                    <option value="200">Larning and Earning Plan -1 @ Rs 200</option>
                                    <option value="500">Larning and Earning Plan -1 @ Rs 500</option>
                                </select>
                                </div>
                            </div>


                            <div class="form-group">
                          </div>

                            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label for="password" class="col-md-4 control-label">Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Register
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/blocks/footer.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: kobid
 * Date: 25-06-2017
 * Time: 17:54
 */